import type { Metadata } from "next";
import { Playfair, Montserrat } from "next/font/google";
import "./globals.css";

const playfair = Playfair({
  variable: "--font-playfair-head",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-monterserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${montserrat.variable} antialiased min-h-full flex flex-col`}
      >
        {children}
      </body>
    </html>
  );
}
